version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: "docker/Dockerfile"

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./__logs__:/var/log/nginx
